apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Production Patch Rollout
on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
        required: true
        description: This is a system-generated parameter and is required for use in application releases. Refer to https://docs.cloudbees.com/docs/cloudbees-platform/latest/applications/releases#manifest for the expected format
metadata:
  stages/v1alpha1:
    - name: DEV
      jobs:
        - Build
    - name: QA
      jobs:
        - hackers-qa
        - Evidence
        - QA_Approval
    - name: PROD
      jobs:
        - hackers-prod
jobs:
  Build:
    steps:
      - with:
          content: |
            # CloudBees Unify - Patch Rollout Evidence Report (Mock)

            ## Release Metadata

            -   **Application:** Payments-Service\
            -   **Patch Version:** v2.3.1-hotfix\
            -   **Release ID:** REL-2026-02-27-001\
            -   **Triggered By:** Git Commit (hotfix/critical-fix)\
            -   **Commit SHA:** a8f5f167f44f4964e6c998dee827110c\
            -   **Jira Ticket:** PAY-4821\
            -   **ServiceNow Change Record:** CHG0093842\
            -   **Report Generated:** 2026-02-27 20:57:36

            ------------------------------------------------------------------------

            ## Stage 1: Build Evidence

            -   **Jenkins Pipeline Triggered:** YES\
            -   **Jenkins Job Name:** payments-service-build\
            -   **Jenkins Build Number:** #1845\
            -   **Jenkins URL:**
                https://jenkins.company.com/job/payments-service-build/1845\
            -   **Build Trigger Source:** Webhook from GitHub (hotfix branch)\
            -   **Agent Used:** k8s-ephemeral-agent-v3.2\
            -   **Build Duration:** 6m 42s\
            -   **Artifact Produced:** payments-service-2.3.1-hotfix.jar\
            -   **Artifact SHA256:** 3ac674216f3e15c761ee1a5e255f067953623c8b\
            -   **Artifact Repository:** Artifactory (libs-release-local)\
            -   **SBOM Generated:** YES (CycloneDX format)\
            -   **Build Status:** SUCCESS

            ------------------------------------------------------------------------

            ## Stage 2: Dev Environment Deployment Evidence

            -   **Deployment Target:** dev-cluster-us-east-1\
            -   **Deployment Strategy:** Rolling Update\
            -   **Deployment Start Time:** 2026-02-27 10:14:23\
            -   **Deployment End Time:** 2026-02-27 10:16:02\
            -   **Environment Approval Required:** NO (auto-approved per policy)\
            -   **Deployment Executed By:** Unify Release Orchestration Workflow\
            -   **Artifact Promoted Without Rebuild:** YES\
            -   **Health Check Endpoint:** /health\
            -   **Health Check Result:** PASS (200 OK)\
            -   **Post-Deployment Smoke Tests:** PASS (5/5 tests successful)\
            -   **Audit Log ID:** AUD-DEV-009128\
            -   **Notification Sent:** Slack #dev-releases channel\
            -   **Deployment Status:** SUCCESS
        uses: cloudbees-io/publish-evidence-item@v1
        name: Call Jenkins
  hackers-prod:
    needs: QA_Approval
    uses: ./.cloudbees/workflows/deployer.yaml
    with:
      manifest: ${{ inputs.manifest }}
      environment: hackers-prod
  hackers-qa:
    needs: Build
    uses: ./.cloudbees/workflows/deployer.yaml
    with:
      manifest: ${{ inputs.manifest }}
      environment: hackers-qa
  Evidence:
    needs: hackers-qa
    steps:
      - with:
          content: |
            # CloudBees Unify - Patch Rollout Evidence Report (Mock)

            ## Stage 3: QA Environment Promotion & Validation Evidence

            ### Release Context

            -   **Application:** Payments-Service\
            -   **Patch Version:** v2.3.1-hotfix\
            -   **Release ID:** REL-2026-02-27-001\
            -   **Artifact Promoted:** payments-service-2.3.1-hotfix.jar\
            -   **Artifact SHA256:** 3ac674216f3e15c761ee1a5e255f067953623c8b\
            -   **Promoted Without Rebuild:** YES\
            -   **Promotion Source:** Dev Environment\
            -   **Promotion Target:** QA Environment\
            -   **Report Generated:** 2026-02-27 21:05:54

            ------------------------------------------------------------------------

            ## QA Approval Gate Evidence

            -   **Approval Required:** YES\
            -   **Approval Type:** Manual (Release Manager + QA Lead)\
            -   **ServiceNow Change Validation:** CHG0093842 in APPROVED state\
            -   **Jira Ticket Validation:** PAY-4821 in Ready for QA state\
            -   **Separation of Duties Enforced:** YES\
            -   **Approvers:**
                -   Jane Smith (QA Lead)\
                -   Michael Tran (Release Manager)\
            -   **Approval Timestamp:** 2026-02-27 12:42:11\
            -   **Policy Checks Evaluated:**
                -   Security Scan Thresholds (No Critical/High findings)\
                -   Test Pass Rate ≥ 95%\
                -   Artifact Fingerprint Match Verified

            ------------------------------------------------------------------------

            ## QA Deployment Execution Evidence

            -   **Deployment Target:** qa-cluster-us-east-1\
            -   **Deployment Strategy:** Blue/Green\
            -   **Deployment Start Time:** 2026-02-27 12:45:03\
            -   **Deployment End Time:** 2026-02-27 12:48:19\
            -   **Executed By:** Unify Release Orchestration Workflow\
            -   **Deployment Status:** SUCCESS

            ------------------------------------------------------------------------

            ## QA Validation Results

            -   **Automated Regression Suite:** PASS (128/128 tests)\
            -   **Integration Tests:** PASS (42/42 tests)\
            -   **Performance Smoke Test:** PASS (P95 latency within SLA)\
            -   **Security Re-Validation Scan:** PASS\
            -   **Defects Identified:** 0 Critical / 0 High / 1 Medium (documented)\
            -   **Defect Linked in Jira:** PAY-4833 (Medium severity cosmetic issue)

            ------------------------------------------------------------------------

            ## Audit & Traceability Evidence

            -   **Audit Log ID:** AUD-QA-009874\
            -   **Artifact Fingerprint Verified Across Environments:** YES\
            -   **Evidence Captured:**
                -   Test Reports (JUnit XML)\
                -   Security Scan Report (SAST/SCA)\
                -   Deployment Logs\
                -   Approval Records\
            -   **Notifications Sent:**
                -   Slack #qa-releases\
                -   Email to release distribution list

            ------------------------------------------------------------------------

            ## QA Stage Outcome

            -   **QA Sign-Off Status:** APPROVED FOR PRODUCTION PROMOTION\
            -   **Rollback Plan Verified:** YES\
            -   **Next Stage:** Production Approval Gate
        uses: cloudbees-io/publish-evidence-item@v1
        name: Gather Evidence
  QA_Approval:
    needs:
      - Evidence
    timeout-minutes: 4320
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
    with:
      instructions: Check Evidence and Approve
      disallowLaunchByUser: false
      notifyAllEligibleUsers: false
      approvers: 3ad0577a-e80d-11ea-a794-42010a83ae1a
