apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Staged release workflow
on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
        required: true
        description: This is a system-generated parameter and is required for use in
          application releases. Refer to
          https://docs.cloudbees.com/docs/cloudbees-platform/latest/applications/releases#manifest
          for the expected format
metadata:
  stages/v1alpha1:
    - name: Pre-prod
      jobs:
        - deploy-pre-prod
    - name: Production
      jobs:
        - SN-approval
        - deploy-production
jobs:
  deploy-pre-prod:
    uses: cloudbees-days/hackers-app/.cloudbees/workflows/deployer.yaml
    with:
      manifest: ${{ inputs.manifest }}
      environment: hacker-pre
    secrets: inherit
    vars: inherit
  SN-approval:
    needs:
      - deploy-pre-prod
    uses: cloudbees-days/hackers-app/.cloudbees/workflows/sn-approval.yaml
    secrets: inherit
    vars: inherit
  deploy-production:
    needs:
      - SN-approval
    steps:
      - name: Deploy
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo Ready to deploy to Production
    #uses: cloudbees-days/hackers-app/.cloudbees/workflows/deployer.yaml
    #with:
      #manifest: ${{ inputs.manifest }}
      #environment: hacker-prod
    #secrets: inherit
