apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Staged release workflow
on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
        required: true
        description: This is a system-generated parameter and is required for use in
          application releases. Refer to
          https://docs.cloudbees.com/docs/cloudbees-platform/latest/applications/releases#manifest
          for the expected format
metadata:
  stages/v1alpha1:
    - name: micro-hacker
      jobs:
        - deploy-to-micro-hacker
jobs:
  deploy-to-micro-hacker:
    steps:
      - name: Deploy to micro-hacker
        uses: cloudbees-days/hackers-app/.cloudbees/workflows/deployer.yaml
        with:
          manifest: ${{ inputs.manifest }}
          environment: micro-hacker