apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Wyndham Workflow
on:
  workflow_dispatch: null
metadata:
  stages/v1alpha1:
    - name: Prod
      jobs:
        - deploy-to-Prod
        - QA_Approval
        - AWS_Admin_Approval
        - Get_Incident_SysId
jobs:
  deploy-to-Prod:
    steps:
      - name: Deploy to Prod
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "Deploying to Prod"
    needs: Get_Incident_SysId
  QA_Approval:
    timeout-minutes: 4320
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
    with:
      instructions: Approve artifacts to go to QA stage
      disallowLaunchByUser: false
      approvers: ""
      notifyAllEligibleUsers: false
  AWS_Admin_Approval:
    needs: QA_Approval
    timeout-minutes: 4320
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
    with:
      instructions: AWS admin approval needed
      disallowLaunchByUser: false
      approvers: ""
      notifyAllEligibleUsers: false
  Get_Incident_SysId:
    outputs:
      SysId: "11092786"
    steps:
      - with:
          content: "# Get SysId"
        uses: cloudbees-io/publish-evidence-item@v1
        name: Incident handler
    needs: AWS_Admin_Approval
